kind: pipeline
name: default

steps:
- name: build
  image: golang:latest
  commands:
  - go get -t ./...
  - go test ./...
  - go build ./...
- name: trigger
  image: plugins/downstream
  settings:
    server: https://drone.jonnrb.com
    token:
      from_secret: drone_token
    fork: true
    repositories:
    - jon/radarsign
