workspace:
  base: /go
  path: src/go.jonnrb.io/speedtest

pipeline:
  build:
    image: golang:latest
    commands:
      - go get -t ./...
      - go test ./...
      - go build ./...

  trigger:
    image: plugins/downstream
    server: https://drone.jonnrb.com
    fork: true
    repositories:
      - jon/radarsign
    secrets: [ downstream_token ]
