kind: pipeline
name: default

workspace:
  base: /go
  path: src/go.jonnrb.io/speedtest

steps:
- name: build
  image: golang:latest
  commands:
  - go get -t ./...
  - go test ./...
  - go build ./...
- name: trigger
  image: plugins/downstream
  config:
    server: https://drone.jonnrb.com
    fork: true
    repositories:
    - jon/radarsign
    token:
      from_secret: downstream_token
