---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:latest
  commands:
  - go get -t ./...
  - go test ./...
  - go build ./...

- name: trigger
  image: plugins/downstream
  settings:
    fork: true
    repositories:
    - jon/radarsign
    server: https://drone.jonnrb.com
    token:
      from_secret: drone_token

...
